url: http://www.thesocial.ee/
baseurl: 

# Site settings
title: The S(@)cial
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Priit Pojev
  pic: 1
  position: General Manager
 #  social:
 #    - title: facebook
 #      url: #

- name: Alex Kukk
  pic: 2
  position: Executive Chef
 #  social:
#     - title: instagram
 #      url: #
 #    - title: facebook
 #      url: #
  #   - title: 
  #     url: #

- name: Annika Varvarova
  pic: 3
  position: Head Chef
 #  social:
  #   - title: instagram
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: google-plus
  #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
